---
name: learn-bosh
director_uuid: 510ac165-ee99-4c45-8274-1b989e5d5697

releases:
- name: learn-bosh
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.0.0/28
    reserved: [10.244.0.1]
    static: [10.244.0.2,10.244.0.6,10.244.0.10]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties:
    admin_password: <%= get_password 'my_admin_password' %> 
    private_key: <%= get_private_key 'my_key' %>
    public_key: <%= get_public_key 'my_key' %>
    cert: <%= get_certificate 'my_cert', 'my_key', '*.example.com' %>
    cert_for_haproxy: <%= get_certificate_and_key 'my_cert', 'my_key', '*.example.com' %>